spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tontine
    username: postgres
    password: fatou
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tontinemanagerff@gmail.com
    password: khvtukakowvkstwo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  mail:
    from: tontinemanagerff@gmail.com
    from-name: Tontine App